version: 2

before:
  hooks:
    - rustup default stable
    - cargo install --locked cargo-zigbuild
    - cargo fetch --locked

builds:
  - builder: rust
    flags:
      - --release
      - --features=self_update
    targets:
      - x86_64-unknown-linux-gnu
      - x86_64-apple-darwin
      - aarch64-unknown-linux-gnu
      - aarch64-apple-darwin
    id: "kubescope"
    binary: kubescope

archives:
  - formats: ["tar.gz"]
    files:
      - none*
    name_template: >-
      {{ .ProjectName }}-{{ .Target }}
    builds:
      - kubescope

changelog:
  disable: true
